/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNull;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertNull("dummy test", null);
    }
}
